    var nome = window.prompt ('Qual é seu nome ? ')
    document.write(`Ola ,<strong>${nome}</strong>, seu nome tem ${nome.length} Letras <br/>`)
    document.write(`Seu nome em maisculas é ${nome.toUpperCase()} <br/>`)
    document.write(`e em minusculo é ${nome.toLowerCase()} <br/> `)
    document.write(`ola ${nome}`)